/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/rex.glb -o src/components/Rex.jsx -r public 
*/

import { useGLTF } from "@react-three/drei";

export function Rex(props: any) {
  const { nodes, materials } = useGLTF("/models/rex.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030upperTeeth_low.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={
          nodes.Rex_Unity_pose_v01T_Rex_Rig_030upperGum_geo_low.geometry
        }
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030rt_upLid_low1.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030rt_pupil_low1.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030rt_loLid_low1.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={
          nodes.Rex_Unity_pose_v01T_Rex_Rig_030rt_highlight_low1.geometry
        }
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030rt_eyebrow_low.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030r_eye_low1.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030lowTeeth_low.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={
          nodes.Rex_Unity_pose_v01T_Rex_Rig_030lowerTongue_geo_low.geometry
        }
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030lf_upLid_low1.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030lf_pupil_low1.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030lf_loLid_low1.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={
          nodes.Rex_Unity_pose_v01T_Rex_Rig_030lf_highlight_low1.geometry
        }
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030lf_eyebrow_low.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030l_eye_low1.geometry}
        material={materials.Shader_B}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rex_Unity_pose_v01T_Rex_Rig_030body_geo_High.geometry}
        material={materials.Shader_A}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/models/rex.glb");
